name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: [self-hosted, andros]
    steps:
      - uses: actions/checkout@v6
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      - name: Lint check
        run: ruff check .

  build:
    needs: lint
    runs-on: [self-hosted, andros]
    steps:
      - uses: actions/checkout@v6
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      - name: Docker build check
        run: docker build -t emcenter-web-test .
